feat: add option to provide extra schemas
b0o/SchemaStore.nvim pull request #14
Opened 2023-04-06 11:12 UTC by williamboman

I also took the liberty to format some of the code according to the
Stylua formatting rules, hope you don't mind!

Supersedes #13.

Closes #9.

2023-05-23 05:01 UTC, b0o requested changes
William, thank you for your contribution, and I apologize for how long it's taken me to review. 

I've left a few review comments, if you have time, please look them over.

2023-05-26 08:28 UTC, williamboman commented on README.md
> +
Yeah for sure! I'm actually not sure why I added it in the first place (also with an incorrect sample).

2023-05-26 09:07 UTC, williamboman commented on README.md
> +
Reverted in c2c1ba9e58a1c8c4e8f0dd39a8ab38321dc1a501.

2023-05-26 09:08 UTC, williamboman commented on test/schemastore.lua
> +      end)
Added tests in e2d792ae9d885f6797313e418d9236d0079e2f59. I might be missing something but `extra + replace` doesn't seem like it was properly supported currently so I had to make some implementation changes as well.

2023-05-26 09:36 UTC, williamboman commented on test/schemastore.lua
> +      end)
Haha nvm I just realized I am the one who's adding `extra` as a new feature 😅. Anyways, wdyt about the proposed implementation change of extending the catalog as a basis for applying the extra schemas?

2023-05-26 09:40 UTC, williamboman commented on lua/schemastore/init.lua
> +    return vim.list_extend({ unpack(opts.extra) }, schemas)
:+1: In my view these extra schemas should simply override the bundled ones (basically `replace`)? Or should it maybe produce an error?

2023-05-26 21:30 UTC, b0o commented
Looks great, thank you William!

2023-05-26 21:31 UTC, b0o approved these changes

2023-05-26 21:31 UTC, merged